"""Renders Equation AST nodes to LaTeX math environments.

Handles two cases:
  1. LaTeX available → render as proper math environment
  2. Only image_path set (MathType/WMF) → render as display math
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from manuscript_compiler.ast.equation import Equation
from manuscript_compiler.journal_profiles import JournalProfile


# Path to the LaTeX mapping file (generated by OCR step)
_LATEX_MAP_PATH = Path("/tmp/formula_latex_map.json")
_latex_map = None


def _load_latex_map() -> dict[str, str]:
    """Load the formula image → LaTeX mapping."""
    global _latex_map
    if _latex_map is None and _LATEX_MAP_PATH.exists():
        try:
            _latex_map = json.loads(_LATEX_MAP_PATH.read_text())
        except Exception:
            _latex_map = {}
    return _latex_map or {}


def render_equations(equations: List[Equation], profile: JournalProfile) -> List[str]:
    """Render all Equation AST nodes to proper LaTeX math."""
    if not equations:
        return []

    latex_map = _load_latex_map()
    lines: List[str] = []
    math_mode_count = 0
    image_mode_count = 0

    for eq in equations:
        rendered = render_single_equation(eq, profile, latex_map)
        if rendered:
            lines.extend(rendered)
            lines.append("")
            # Track what kind of rendering was used
            if eq.latex:
                math_mode_count += 1
            else:
                image_mode_count += 1

    if image_mode_count > 0:
        lines.append(
            r"% " + f"Note: {image_mode_count} formula(s) still use image placeholders. "
            r"Run formula_ocr.py to convert to LaTeX."
        )
        lines.append("")

    return lines


def render_single_equation(
    eq: Equation,
    profile: JournalProfile,
    latex_map: dict[str, str] | None = None,
) -> List[str]:
    """Render a single Equation to LaTeX."""
    lines: List[str] = []
    latex_code = ""

    # Priority 1: Already have LaTeX code in the AST
    if eq.latex:
        latex_code = eq.latex

    # Priority 2: Look up by image path in the OCR mapping
    if not latex_code and eq.image_path and latex_map:
        img_name = Path(eq.image_path).name
        if img_name in latex_map:
            latex_code = latex_map[img_name]

    # Case A: We have real LaTeX — use proper math environment
    if latex_code:
        if eq.inline:
            # Strip any existing $ delimiters to avoid $$...$$
            clean = latex_code.strip().strip("$").strip()
            lines.append(f"${clean}$")
        else:
            lines.append(r"\begin{equation}")
            lines.append(latex_code)
            # Use bound number if available, otherwise fall back to eq.id
            label_key = eq.number.strip("()") if eq.number else eq.id
            if label_key:
                lines.append(r"\label{" + f"eq:{label_key}" + "}")
            lines.append(r"\end{equation}")
        return lines

    # Case B: Only formula image available — use image placeholder
    if eq.image_path:
        img_name = Path(eq.image_path).name
        lines.append(r"\begin{equation}")
        lines.append(r"\includegraphics[width=0.3\columnwidth]{" + img_name + "}")
        if eq.id:
            lines.append(r"\label{" + f"eq:{eq.id}" + "}")
        lines.append(r"\end{equation}")
        lines.append(r"% TODO: Convert formula image to LaTeX")
        return lines

    # Case C: Nothing
    return []
